name: example-environment
channels:
  - esri
  - conda-forge
  - fastai
  - pytorch

dependencies:
  - python
  - numpy
  - pip
  - matplotlib
  - seaborn
  - arcgis
  - scipy
  - pillow
  - numpy
  - fastai=1.0.54
  - torchvision=0.3.0
  - pytorch=1.1.0
  - cudatoolkit

  - pip:
    - arcgis
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib