name: arcgis-environment
channels:
  - esri
  - conda-forge
  - fastai
  - pytorch

dependencies:
  - python=3.6
  - fiona
  - scikit-learn
  - numpy
  - pandas >=0.23
  - pip
  - matplotlib
  - seaborn
  - arcgis
  - scipy
  - pillow
  - numpy
  - fastai=1.0.54
  - torchvision=0.3.0
  - pytorch=1.1.0
  - cudatoolkit

  - pip:
    - nbgitpuller
    - sphinx-gallery
    - matplotlib